name: Daily Job Pipeline

on:
  schedule:
    - cron: "30 2 * * *"
  workflow_dispatch:

jobs:
  run-pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Get the code
        uses: actions/checkout@v4